# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "xp-functions"
client_id = "00789e9cb1b38d203f59e9c4ddf12045"
application_url = "https://albuquerque-bold-fireplace-webmaster.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products, write_discounts"

[auth]
redirect_urls = [
  "https://albuquerque-bold-fireplace-webmaster.trycloudflare.com/auth/callback",
  "https://albuquerque-bold-fireplace-webmaster.trycloudflare.com/auth/shopify/callback",
  "https://albuquerque-bold-fireplace-webmaster.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2023-10"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "shadyrays-post-purchase.myshopify.com"
